# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8154a751d7956047fed8ae1675c53b86ea3ec1dc04c90db4a649e12449d663e2c4202a0141d419eaff7fcdba284c848ad7e5beb648eaae2d5a9a17629894a7c

test:
  secret_key_base: 854ceed69df9823ccfaf4f208aaa6f6c96cb1b9bdad2853aeeacaa5ed062d28db37dfc5e4e925e07d925324d63dd6b394e937f78eaa2b969bf03d3fe475187c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
